/**
 * Generates a pretty HTML Bill of Materials report.
 */

import { getMaterialById } from '../data/materials';

export function generateBomHtml(bomRows, totalCost, projectName = 'Untitled') {
  const rows = bomRows.map((row) => {
    const material = getMaterialById(row.material);
    const color = material?.color || '#888';
    return `<tr>
      <td>${row.partName}</td>
      <td><span style="display:inline-block;width:12px;height:12px;border-radius:2px;background:${color};margin-right:6px;vertical-align:middle;"></span>${row.materialName || row.material || '-'}</td>
      <td>${Math.round(row.width)}</td>
      <td>${Math.round(row.height)}</td>
      <td>${row.thickness || '-'}</td>
      <td>${row.quantity}</td>
      <td>${row.totalCost > 0 ? '$' + row.totalCost.toFixed(2) : '-'}</td>
    </tr>`;
  }).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${projectName} — Cutting List</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #333; }
  h1 { font-size: 24px; border-bottom: 2px solid #f5a623; padding-bottom: 8px; }
  table { width: 100%; border-collapse: collapse; margin: 20px 0; }
  th { background: #f5f5f5; padding: 8px 12px; text-align: left; font-size: 12px; text-transform: uppercase; color: #666; border-bottom: 2px solid #ddd; }
  td { padding: 8px 12px; border-bottom: 1px solid #eee; font-size: 14px; }
  tr:hover td { background: #fafafa; }
  .total { font-size: 20px; font-weight: 700; color: #f5a623; margin: 20px 0; }
  .footer { font-size: 11px; color: #999; margin-top: 40px; border-top: 1px solid #eee; padding-top: 12px; }
</style>
</head>
<body>
<h1>${projectName} — Cutting List</h1>
<table>
  <thead>
    <tr><th>Part</th><th>Material</th><th>Width (mm)</th><th>Height (mm)</th><th>Thickness</th><th>Qty</th><th>Cost</th></tr>
  </thead>
  <tbody>
    ${rows}
  </tbody>
</table>
<p class="total">Total Estimated Cost: $${totalCost.toFixed(2)}</p>
<p class="footer">Generated by Craftsman Studio</p>
</body>
</html>`;
}
