/**
 * Full-scale PDF export via browser print.
 * Pure print content builders remain testable without DOM; printEntities is the thin browser wrapper.
 */

import { buildSvgExportDocument } from './svgExport';

/** Default caption. Kept verbatim so existing PDF output stays byte-identical. */
const DEFAULT_RULER_CAPTION = '100mm ruler - verify with a physical ruler';

/**
 * A 100.0mm scale-check ruler: the one mark on the sheet that tells the maker
 * whether the printer really printed 1:1. `label` is the caption under the bar;
 * callers that pass nothing get exactly the string this export has always used.
 *
 * The ruler occupies 13mm ABOVE the baseline (8mm ticks plus the numerals) and
 * 6mm below it, which is the box a caller has to reserve when placing it.
 */
export function buildRulerSvg(x, y, options = {}) {
  const caption = options.label ?? DEFAULT_RULER_CAPTION;
  let ruler = `<g transform="translate(${x}, ${y})" stroke="black" stroke-width="0.3" fill="none">`;
  ruler += '<line x1="0" y1="0" x2="100" y2="0" />';
  for (let index = 0; index <= 100; index += 10) {
    const height = index % 50 === 0 ? 8 : 4;
    ruler += `<line x1="${index}" y1="0" x2="${index}" y2="${-height}" />`;
    ruler += `<text x="${index}" y="-10" font-size="3" text-anchor="middle" fill="black" font-family="sans-serif">${index}</text>`;
  }
  ruler += `<text x="50" y="6" font-size="2.5" text-anchor="middle" fill="black" font-family="sans-serif">${caption}</text>`;
  ruler += '</g>';
  return ruler;
}

export function buildPrintableSvg(entities, options = {}) {
  const document = buildSvgExportDocument(entities, options);
  const svgHeight = document.bounds.height + 15;
  const rulerX = document.bounds.x + 5;
  // Below the document body, inside the 15mm the sheet adds for it: the bottom of
  // the bounds is no longer guaranteed to be empty margin now that the hardware
  // legend can occupy it.
  const rulerY = document.bounds.y + document.bounds.height + 8;

  return `<svg xmlns="http://www.w3.org/2000/svg"
     width="${document.bounds.width}mm" height="${svgHeight}mm"
     viewBox="${document.bounds.x} ${document.bounds.y} ${document.bounds.width} ${svgHeight}">
  <!-- Generated by Craftsman Studio -->
${document.elements.join('\n')}
  ${buildRulerSvg(rulerX, rulerY)}
</svg>`;
}

export function buildPrintDocumentHtml(entities, options = {}) {
  const svgString = buildPrintableSvg(entities, options);

  return `<!DOCTYPE html>
<html>
<head>
<style>
  @page { margin: 5mm; }
  body { margin: 0; padding: 0; }
  svg { display: block; max-width: 100%; height: auto; }
  .print-note { font-family: sans-serif; font-size: 10px; color: #666; margin: 2mm 0; }
</style>
</head>
<body>
  <p class="print-note">Craftsman Studio - set "Scale: 100%" and "Margins: None" for true 1:1 output</p>
  ${svgString}
</body>
</html>`;
}

/**
 * Print an arbitrary HTML document through a throwaway hidden iframe.
 *
 * This is the whole browser surface of PDF export: everything else in this
 * module (and in `templatePdfExport`) is a pure string builder that a node test
 * can run. Shared so the tiled full-scale templates print through exactly the
 * same path as the single-sheet PDF.
 */
export function printHtmlDocument(html) {
  const iframe = document.createElement('iframe');
  iframe.style.position = 'fixed';
  iframe.style.left = '-9999px';
  iframe.style.width = '0';
  iframe.style.height = '0';
  document.body.appendChild(iframe);

  const iframeDocument = iframe.contentDocument || iframe.contentWindow.document;
  iframeDocument.open();
  iframeDocument.write(html);
  iframeDocument.close();

  iframe.contentWindow.focus();
  iframe.contentWindow.print();

  setTimeout(() => {
    document.body.removeChild(iframe);
  }, 1000);
}

export function printEntities(entities, options = {}) {
  printHtmlDocument(buildPrintDocumentHtml(entities, options));
}
