/**
 * Full-scale PDF export via browser print.
 * Pure print content builders remain testable without DOM; printEntities is the thin browser wrapper.
 */

import { buildSvgExportDocument } from './svgExport';

function buildRulerSvg(x, y) {
  let ruler = `<g transform="translate(${x}, ${y})" stroke="black" stroke-width="0.3" fill="none">`;
  ruler += '<line x1="0" y1="0" x2="100" y2="0" />';
  for (let index = 0; index <= 100; index += 10) {
    const height = index % 50 === 0 ? 8 : 4;
    ruler += `<line x1="${index}" y1="0" x2="${index}" y2="${-height}" />`;
    ruler += `<text x="${index}" y="-10" font-size="3" text-anchor="middle" fill="black" font-family="sans-serif">${index}</text>`;
  }
  ruler += '<text x="50" y="6" font-size="2.5" text-anchor="middle" fill="black" font-family="sans-serif">100mm ruler - verify with a physical ruler</text>';
  ruler += '</g>';
  return ruler;
}

export function buildPrintableSvg(entities, options = {}) {
  const document = buildSvgExportDocument(entities, options);
  const svgHeight = document.bounds.height + 15;
  const rulerX = document.bounds.x + 5;
  const rulerY = document.bounds.y + document.bounds.height - 5;

  return `<svg xmlns="http://www.w3.org/2000/svg"
     width="${document.bounds.width}mm" height="${svgHeight}mm"
     viewBox="${document.bounds.x} ${document.bounds.y} ${document.bounds.width} ${svgHeight}">
  <!-- Generated by Craftsman Studio -->
${document.elements.join('\n')}
  ${buildRulerSvg(rulerX, rulerY)}
</svg>`;
}

export function buildPrintDocumentHtml(entities, options = {}) {
  const svgString = buildPrintableSvg(entities, options);

  return `<!DOCTYPE html>
<html>
<head>
<style>
  @page { margin: 5mm; }
  body { margin: 0; padding: 0; }
  svg { display: block; max-width: 100%; height: auto; }
  .print-note { font-family: sans-serif; font-size: 10px; color: #666; margin: 2mm 0; }
</style>
</head>
<body>
  <p class="print-note">Craftsman Studio - set "Scale: 100%" and "Margins: None" for true 1:1 output</p>
  ${svgString}
</body>
</html>`;
}

export function printEntities(entities, options = {}) {
  const html = buildPrintDocumentHtml(entities, options);

  const iframe = document.createElement('iframe');
  iframe.style.position = 'fixed';
  iframe.style.left = '-9999px';
  iframe.style.width = '0';
  iframe.style.height = '0';
  document.body.appendChild(iframe);

  const iframeDocument = iframe.contentDocument || iframe.contentWindow.document;
  iframeDocument.open();
  iframeDocument.write(html);
  iframeDocument.close();

  iframe.contentWindow.focus();
  iframe.contentWindow.print();

  setTimeout(() => {
    document.body.removeChild(iframe);
  }, 1000);
}
