/**
 * Standalone SVG export with correct mm dimensions.
 * Produces clean SVG suitable for laser cutters and CNC.
 */

import { downloadAsFile } from '../../utils/bomExportUtils';

function entityToSvgElement(entity) {
  switch (entity.type) {
    case 'line':
      return `  <line x1="${entity.x1}" y1="${entity.y1}" x2="${entity.x2}" y2="${entity.y2}" stroke="black" stroke-width="0.5" fill="none" />`;

    case 'rect': {
      const x = Math.min(entity.x1 ?? entity.x ?? 0, entity.x2 ?? ((entity.x ?? 0) + (entity.width ?? 0)));
      const y = Math.min(entity.y1 ?? entity.y ?? 0, entity.y2 ?? ((entity.y ?? 0) + (entity.height ?? 0)));
      const w = Math.abs(entity.width ?? ((entity.x2 ?? 0) - (entity.x1 ?? 0)));
      const h = Math.abs(entity.height ?? ((entity.y2 ?? 0) - (entity.y1 ?? 0)));
      return `  <rect x="${x}" y="${y}" width="${w}" height="${h}" stroke="black" stroke-width="0.5" fill="none" />`;
    }

    case 'circle': {
      const cx = entity.center?.x ?? entity.cx ?? 0;
      const cy = entity.center?.y ?? entity.cy ?? 0;
      const r = entity.radius ?? 0;
      return `  <circle cx="${cx}" cy="${cy}" r="${r}" stroke="black" stroke-width="0.5" fill="none" />`;
    }

    case 'ellipse': {
      const cx = entity.cx ?? 0;
      const cy = entity.cy ?? 0;
      const rx = entity.rx ?? entity.radius ?? 0;
      const ry = entity.ry ?? entity.radius ?? 0;
      return `  <ellipse cx="${cx}" cy="${cy}" rx="${rx}" ry="${ry}" stroke="black" stroke-width="0.5" fill="none" />`;
    }

    case 'polyline': {
      if (!entity.points?.length) return '';
      const pts = entity.points.map((p) => `${p.x},${p.y}`).join(' ');
      const tag = entity.closed ? 'polygon' : 'polyline';
      return `  <${tag} points="${pts}" stroke="black" stroke-width="0.5" fill="none" />`;
    }

    case 'arc': {
      if (!entity.start || !entity.end) return '';
      const r = Math.hypot(entity.end.x - entity.start.x, entity.end.y - entity.start.y) / 2;
      return `  <path d="M ${entity.start.x} ${entity.start.y} A ${r} ${r} 0 0 1 ${entity.end.x} ${entity.end.y}" stroke="black" stroke-width="0.5" fill="none" />`;
    }

    default:
      return '';
  }
}

const EXPORTABLE_TYPES = new Set(['line', 'rect', 'circle', 'arc', 'polyline', 'ellipse']);

function computeBounds(entities) {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;

  for (const e of entities) {
    const pts = getPoints(e);
    for (const p of pts) {
      if (p.x < minX) minX = p.x;
      if (p.y < minY) minY = p.y;
      if (p.x > maxX) maxX = p.x;
      if (p.y > maxY) maxY = p.y;
    }
  }

  if (!Number.isFinite(minX)) return { x: 0, y: 0, width: 100, height: 100 };
  const margin = 10;
  return {
    x: minX - margin,
    y: minY - margin,
    width: (maxX - minX) + margin * 2,
    height: (maxY - minY) + margin * 2,
  };
}

function getPoints(entity) {
  switch (entity.type) {
    case 'line': return [{ x: entity.x1, y: entity.y1 }, { x: entity.x2, y: entity.y2 }];
    case 'rect': {
      const x = entity.x1 ?? entity.x ?? 0;
      const y = entity.y1 ?? entity.y ?? 0;
      const w = Math.abs(entity.width ?? ((entity.x2 ?? 0) - (entity.x1 ?? 0)));
      const h = Math.abs(entity.height ?? ((entity.y2 ?? 0) - (entity.y1 ?? 0)));
      return [{ x, y }, { x: x + w, y: y + h }];
    }
    case 'circle': {
      const cx = entity.center?.x ?? entity.cx ?? 0;
      const cy = entity.center?.y ?? entity.cy ?? 0;
      const r = entity.radius ?? 0;
      return [{ x: cx - r, y: cy - r }, { x: cx + r, y: cy + r }];
    }
    case 'polyline': return entity.points ?? [];
    default: return [];
  }
}

export function exportEntitiesToSvg(entities, options = {}) {
  const exportable = entities.filter((e) => EXPORTABLE_TYPES.has(e.type));
  const filtered = options.selectedOnly
    ? exportable.filter((e) => options.selectedIds?.includes(e.id))
    : exportable;

  const bounds = computeBounds(filtered);
  const elements = filtered.map(entityToSvgElement).filter(Boolean).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     width="${bounds.width}mm" height="${bounds.height}mm"
     viewBox="${bounds.x} ${bounds.y} ${bounds.width} ${bounds.height}">
  <!-- Generated by Craftsman Studio -->
${elements}
</svg>`;
}

export function downloadSvg(entities, filename = 'sketch.svg', options = {}) {
  const content = exportEntitiesToSvg(entities, options);
  downloadAsFile(content, filename, 'image/svg+xml');
}
