/**
 * One-click workshop export.
 * Pure package assembly lives in buildWorkshopPackageContents; ZIP download stays in generateWorkshopZip.
 */

import JSZip from 'jszip';
import { exportBomWithCost } from '../../utils/bomExportUtils';
import { generateAssemblyHtml } from './assemblyHtmlExport';
import { generateBomHtml } from './bomHtmlExport';
import { exportEntitiesToDxf } from './dxfExport';
import { buildNestedSheetFilename, exportNestedSheetsToDxf } from './nestedDxfExport';
import { exportEntitiesToSvg } from './svgExport';
import { generateAssemblySteps } from '../utils/assemblyGenerator';
import { buildBomEntityList, isHardwareBomRow } from '../utils/entityBomAdapter';

const NESTED_SHEETS_FOLDER = 'sheets';

function sanitizeFilename(name) {
  return name.replace(/[^a-zA-Z0-9_\- ]/g, '').trim() || 'Untitled';
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

function buildNestedSheetsReadmeLine(sheetCount) {
  if (!sheetCount) {
    return [];
  }

  const firstSheet = buildNestedSheetFilename(0, sheetCount);
  const lastSheet = buildNestedSheetFilename(sheetCount - 1, sheetCount);
  const range = sheetCount === 1 ? lastSheet : `${firstSheet} .. ${lastSheet}`;

  return [
    `  ${NESTED_SHEETS_FOLDER}/${range} - ${sheetCount} nested sheet${sheetCount === 1 ? '' : 's'}, one DXF per sheet of stock (stock outline on layer SHEET, parts cut-ready in place)`,
  ];
}

/**
 * How the package documents hardware, and how many fasteners it expects. The
 * count comes from the BOM rows the sidebar already grouped, so it matches the
 * cutting list and the assembly instructions.
 */
function buildHardwareReadmeLines(name, bomRows, sheetCount = 0, skippedFasteners = 0) {
  const hardwareRows = (bomRows || []).filter(isHardwareBomRow);

  if (!hardwareRows.length) {
    return [];
  }

  const totalFasteners = hardwareRows.reduce((sum, row) => sum + (Number(row.quantity) || 1), 0);

  return [
    '',
    'Hardware:',
    `  ${totalFasteners} fastener(s) across ${hardwareRows.length} catalog item(s) - see the Hardware section of cutting-list.html`,
    '  and the "Hardware needed" list in assembly-instructions.html.',
    `  ${name}.dxf puts every placed fastener on the HARDWARE layer as a true CIRCLE at its pilot diameter.`,
    '  Those circles are drill centres, not cut paths: kerf compensation is never applied to them.',
    `  ${name}.svg (and the 1:1 PDF print) marks each fastener F1, F2, ... with a matching HARDWARE LEGEND block.`,
    ...(sheetCount
      ? [`  ${NESTED_SHEETS_FOLDER}/ repeats each part's own fasteners on its sheet, on the same HARDWARE layer.`]
      : []),
    ...(skippedFasteners
      ? [
          `  WARNING: ${skippedFasteners} fastener(s) were left off the nested sheets because their centre no longer`,
          '  lands on the part they were placed against. Re-place them over the part before drilling.',
        ]
      : []),
  ];
}

function buildWorkshopReadme(name, errors, bomRows, sheetCount = 0, skippedFasteners = 0) {
  const approximateRows = (bomRows || []).filter(
    (row) => row.dimensionAccuracy === 'approximate' || row.costAccuracy === 'approximate',
  );

  return [
    `${name} - Workshop Package`,
    'Generated by Craftsman Studio',
    '',
    'Contents:',
    `  ${name}.dxf - CNC/laser-ready vector file (cuts on layer 0, drilled fasteners on layer HARDWARE)`,
    ...buildNestedSheetsReadmeLine(sheetCount),
    `  ${name}.svg - Vector file for Inkscape/Illustrator, with the hardware legend`,
    '  cutting-list.csv - Bill of Materials (spreadsheet)',
    '  cutting-list.html - BOM report (open in browser)',
    '  assembly-instructions.html - Step-by-step build guide',
    ...buildHardwareReadmeLines(name, bomRows, sheetCount, skippedFasteners),
    '',
    'For full-scale PDF printing, use the PDF export button in Craftsman Studio.',
    'Set your browser print dialog to "Scale: 100%" and "Margins: None".',
    '',
    approximateRows.length
      ? `BOM note: ${approximateRows.length} row(s) include approximate dimensions or cost estimates. Check the BOM report status column before manufacturing.`
      : 'BOM note: all exported BOM rows are marked exact under the current geometry model.',
    '',
    errors.length ? `Warnings during export:\n  ${errors.join('\n  ')}` : 'All files exported successfully.',
  ].join('\n');
}

export function buildWorkshopPackageContents(
  entities,
  bomRows,
  totalCost,
  costByMaterial,
  projectName = 'Untitled',
  options = {},
) {
  const name = sanitizeFilename(projectName);
  const folderName = `${name}-Workshop`;
  const referenceEntities = options.referenceEntities ?? entities;
  const files = [];
  const errors = [];
  let nestedSheetCount = 0;
  let skippedFasteners = 0;

  try {
    files.push({
      name: `${name}.dxf`,
      content: exportEntitiesToDxf(entities, {
        kerf: options.kerf,
        referenceEntities: options.referenceEntities,
      }),
    });
  } catch (error) {
    errors.push(`DXF: ${error.message}`);
  }

  try {
    // One cut file per nested sheet of stock. Projects with no sheet-stock parts
    // (all-linear or empty BOM) simply contribute no files and no warning.
    const nestedSheets = exportNestedSheetsToDxf(entities, bomRows, {
      kerf: options.kerf,
      sheetSize: options.sheetSize,
      bladeKerf: options.bladeKerf,
    });
    nestedSheetCount = nestedSheets.length;
    nestedSheets.forEach((sheet) => {
      skippedFasteners += sheet.skippedFasteners || 0;
      files.push({
        name: `${NESTED_SHEETS_FOLDER}/${sheet.filename}`,
        content: sheet.content,
      });
    });
  } catch (error) {
    nestedSheetCount = 0;
    errors.push(`Nested sheet DXF: ${error.message}`);
  }

  try {
    files.push({
      name: `${name}.svg`,
      content: exportEntitiesToSvg(entities, {
        referenceEntities: options.referenceEntities,
      }),
    });
  } catch (error) {
    errors.push(`SVG: ${error.message}`);
  }

  try {
    files.push({
      name: 'cutting-list.csv',
      content: exportBomWithCost(bomRows, 'csv', { rows: bomRows, totalCost, costByMaterial }),
    });
  } catch (error) {
    errors.push(`BOM CSV: ${error.message}`);
  }

  try {
    files.push({
      name: 'cutting-list.html',
      content: generateBomHtml(bomRows, totalCost, name),
    });
  } catch (error) {
    errors.push(`BOM HTML: ${error.message}`);
  }

  try {
    // Same entity list the sidebar's assembly panel and the BOM are built from:
    // parts from the document (so the manufacturing set's cloned panels and
    // generated cut profiles cannot be mistaken for extra parts) plus the
    // joinery-generated features that consume a fastener. Callers that pass no
    // `referenceEntities` keep the previous single-list behaviour.
    files.push({
      name: 'assembly-instructions.html',
      content: generateAssemblyHtml(generateAssemblySteps(buildBomEntityList(referenceEntities, entities)), name),
    });
  } catch (error) {
    errors.push(`Assembly: ${error.message}`);
  }

  files.push({
    name: 'README.txt',
    content: buildWorkshopReadme(name, errors, bomRows, nestedSheetCount, skippedFasteners),
  });

  return {
    folderName,
    files,
    errors,
  };
}

export async function generateWorkshopZip(
  entities,
  bomRows,
  totalCost,
  costByMaterial,
  projectName = 'Untitled',
  options = {},
) {
  const packageContents = buildWorkshopPackageContents(
    entities,
    bomRows,
    totalCost,
    costByMaterial,
    projectName,
    options,
  );

  const zip = new JSZip();
  const folder = zip.folder(packageContents.folderName);
  packageContents.files.forEach((file) => {
    folder.file(file.name, file.content);
  });

  const blob = await zip.generateAsync({ type: 'blob' });
  downloadBlob(blob, `${packageContents.folderName}.zip`);

  return {
    errors: packageContents.errors,
    fileCount: packageContents.files.length,
  };
}
