/**
 * One-click workshop export.
 * Pure package assembly lives in buildWorkshopPackageContents; ZIP download stays in generateWorkshopZip.
 */

import JSZip from 'jszip';
import { exportBomWithCost } from '../../utils/bomExportUtils';
import { generateAssemblyHtml } from './assemblyHtmlExport';
import { generateBomHtml } from './bomHtmlExport';
import { exportEntitiesToDxf } from './dxfExport';
import { exportEntitiesToSvg } from './svgExport';
import { generateAssemblySteps } from '../utils/assemblyGenerator';

function sanitizeFilename(name) {
  return name.replace(/[^a-zA-Z0-9_\- ]/g, '').trim() || 'Untitled';
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

function buildWorkshopReadme(name, errors, bomRows) {
  const approximateRows = (bomRows || []).filter((row) => row.dimensionAccuracy === 'approximate' || row.costAccuracy === 'approximate');

  return [
    `${name} - Workshop Package`,
    'Generated by Craftsman Studio',
    '',
    'Contents:',
    `  ${name}.dxf - CNC/laser-ready vector file`,
    `  ${name}.svg - Vector file for Inkscape/Illustrator`,
    '  cutting-list.csv - Bill of Materials (spreadsheet)',
    '  cutting-list.html - BOM report (open in browser)',
    '  assembly-instructions.html - Step-by-step build guide',
    '',
    'For full-scale PDF printing, use the PDF export button in Craftsman Studio.',
    'Set your browser print dialog to "Scale: 100%" and "Margins: None".',
    '',
    approximateRows.length
      ? `BOM note: ${approximateRows.length} row(s) include approximate dimensions or cost estimates. Check the BOM report status column before manufacturing.`
      : 'BOM note: all exported BOM rows are marked exact under the current geometry model.',
    '',
    errors.length ? `Warnings during export:\n  ${errors.join('\n  ')}` : 'All files exported successfully.',
  ].join('\n');
}

export function buildWorkshopPackageContents(
  entities,
  bomRows,
  totalCost,
  costByMaterial,
  projectName = 'Untitled',
  options = {},
) {
  const name = sanitizeFilename(projectName);
  const folderName = `${name}-Workshop`;
  const files = [];
  const errors = [];

  try {
    files.push({
      name: `${name}.dxf`,
      content: exportEntitiesToDxf(entities, {
        kerf: options.kerf,
        referenceEntities: options.referenceEntities,
      }),
    });
  } catch (error) {
    errors.push(`DXF: ${error.message}`);
  }

  try {
    files.push({
      name: `${name}.svg`,
      content: exportEntitiesToSvg(entities, {
        referenceEntities: options.referenceEntities,
      }),
    });
  } catch (error) {
    errors.push(`SVG: ${error.message}`);
  }

  try {
    files.push({
      name: 'cutting-list.csv',
      content: exportBomWithCost(bomRows, 'csv', { rows: bomRows, totalCost, costByMaterial }),
    });
  } catch (error) {
    errors.push(`BOM CSV: ${error.message}`);
  }

  try {
    files.push({
      name: 'cutting-list.html',
      content: generateBomHtml(bomRows, totalCost, name),
    });
  } catch (error) {
    errors.push(`BOM HTML: ${error.message}`);
  }

  try {
    files.push({
      name: 'assembly-instructions.html',
      content: generateAssemblyHtml(generateAssemblySteps(entities), name),
    });
  } catch (error) {
    errors.push(`Assembly: ${error.message}`);
  }

  files.push({
    name: 'README.txt',
    content: buildWorkshopReadme(name, errors, bomRows),
  });

  return {
    folderName,
    files,
    errors,
  };
}

export async function generateWorkshopZip(
  entities,
  bomRows,
  totalCost,
  costByMaterial,
  projectName = 'Untitled',
  options = {},
) {
  const packageContents = buildWorkshopPackageContents(
    entities,
    bomRows,
    totalCost,
    costByMaterial,
    projectName,
    options,
  );

  const zip = new JSZip();
  const folder = zip.folder(packageContents.folderName);
  packageContents.files.forEach((file) => {
    folder.file(file.name, file.content);
  });

  const blob = await zip.generateAsync({ type: 'blob' });
  downloadBlob(blob, `${packageContents.folderName}.zip`);

  return {
    errors: packageContents.errors,
    fileCount: packageContents.files.length,
  };
}
