/**
 * One-click workshop export — generates a ZIP containing all project files.
 * DXF + SVG + BOM CSV + BOM HTML + Assembly HTML + README
 */

import JSZip from 'jszip';
import { exportEntitiesToDxf } from './dxfExport';
import { exportEntitiesToSvg } from './svgExport';
import { exportBomWithCost } from '../../utils/bomExportUtils';
import { generateBomHtml } from './bomHtmlExport';
import { generateAssemblyHtml } from './assemblyHtmlExport';
import { generateAssemblySteps } from '../utils/assemblyGenerator';

function sanitizeFilename(name) {
  return name.replace(/[^a-zA-Z0-9_\- ]/g, '').trim() || 'Untitled';
}

export async function generateWorkshopZip(entities, bomRows, totalCost, costByMaterial, projectName = 'Untitled', options = {}) {
  const zip = new JSZip();
  const name = sanitizeFilename(projectName);
  const folder = zip.folder(`${name}-Workshop`);
  const errors = [];

  // DXF
  try {
    const dxf = exportEntitiesToDxf(entities, { kerf: options.kerf });
    folder.file(`${name}.dxf`, dxf);
  } catch (e) { errors.push(`DXF: ${e.message}`); }

  // SVG
  try {
    const svg = exportEntitiesToSvg(entities);
    folder.file(`${name}.svg`, svg);
  } catch (e) { errors.push(`SVG: ${e.message}`); }

  // BOM CSV
  try {
    const csv = exportBomWithCost(bomRows, 'csv', { rows: bomRows, totalCost, costByMaterial });
    folder.file('cutting-list.csv', csv);
  } catch (e) { errors.push(`BOM CSV: ${e.message}`); }

  // BOM HTML
  try {
    const html = generateBomHtml(bomRows, totalCost, name);
    folder.file('cutting-list.html', html);
  } catch (e) { errors.push(`BOM HTML: ${e.message}`); }

  // Assembly Instructions
  try {
    const assembly = generateAssemblySteps(entities);
    const assemblyHtml = generateAssemblyHtml(assembly, name);
    folder.file('assembly-instructions.html', assemblyHtml);
  } catch (e) { errors.push(`Assembly: ${e.message}`); }

  // README
  folder.file('README.txt', [
    `${name} — Workshop Package`,
    `Generated by Craftsman Studio`,
    ``,
    `Contents:`,
    `  ${name}.dxf           — CNC/laser-ready vector file`,
    `  ${name}.svg           — Vector file for Inkscape/Illustrator`,
    `  cutting-list.csv      — Bill of Materials (spreadsheet)`,
    `  cutting-list.html     — Pretty BOM report (open in browser)`,
    `  assembly-instructions.html — Step-by-step build guide`,
    ``,
    `For full-scale PDF printing, use the PDF export button in Craftsman Studio.`,
    `Set your browser print dialog to "Scale: 100%" and "Margins: None".`,
    ``,
    errors.length ? `Warnings during export:\n  ${errors.join('\n  ')}` : 'All files exported successfully.',
  ].join('\n'));

  const blob = await zip.generateAsync({ type: 'blob' });

  // Trigger download
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${name}-Workshop.zip`;
  a.click();
  URL.revokeObjectURL(url);

  return { errors, fileCount: 5 - errors.length + 1 }; // +1 for README always present
}
