-- Seed writing prompts (150 prompts across categories)
INSERT INTO writing_prompts (prompt_text, category) VALUES
-- Introspection (30)
('What would you tell your 16-year-old self?', 'introspection'),
('Describe a belief you held strongly that you''ve since changed your mind about.', 'introspection'),
('What''s the most important lesson you learned the hard way?', 'introspection'),
('Write about a moment that changed the way you see the world.', 'introspection'),
('What are you pretending not to know?', 'introspection'),
('Describe the version of yourself you''re becoming.', 'introspection'),
('What would you do if you knew you couldn''t fail?', 'introspection'),
('Write about something you''re grateful for that you usually take for granted.', 'introspection'),
('What does your ideal ordinary day look like?', 'introspection'),
('Write a letter to someone who shaped who you are today.', 'introspection'),
('What''s a question you''re afraid to answer honestly?', 'introspection'),
('Describe a time you chose courage over comfort.', 'introspection'),
('What would you want people to say about you at your funeral?', 'introspection'),
('Write about the last time you surprised yourself.', 'introspection'),
('What''s the bravest thing you''ve ever done?', 'introspection'),
('If your life had a theme song, what would it be and why?', 'introspection'),
('What are you most proud of that no one knows about?', 'introspection'),
('Describe the moment you realized you were an adult.', 'introspection'),
('What''s something you need to forgive yourself for?', 'introspection'),
('Write about a crossroads moment in your life.', 'introspection'),
('What does "enough" mean to you?', 'introspection'),
('Describe your relationship with time.', 'introspection'),
('What would you do differently if you could relive last year?', 'introspection'),
('Write about a fear you''ve overcome.', 'introspection'),
('What makes you feel most alive?', 'introspection'),
('Describe something you''re holding onto that you should let go of.', 'introspection'),
('What''s the kindest thing anyone has ever done for you?', 'introspection'),
('Write about a moment of unexpected joy.', 'introspection'),
('What does home mean to you beyond a physical place?', 'introspection'),
('If you could have dinner with any version of yourself, which age would you choose?', 'introspection'),

-- Creative (30)
('Write a story that begins and ends with the same sentence.', 'creative'),
('Describe a color to someone who has never seen it.', 'creative'),
('Write from the perspective of an object in your room.', 'creative'),
('Create a myth to explain why the sky changes color at sunset.', 'creative'),
('Write a conversation between two strangers who will never meet again.', 'creative'),
('Describe the taste of your favorite memory.', 'creative'),
('Write a story in exactly 100 words.', 'creative'),
('Imagine finding a door in your house you''ve never noticed before. What''s behind it?', 'creative'),
('Write a love letter to something abstract (time, silence, chaos).', 'creative'),
('Describe a sound that doesn''t exist yet but should.', 'creative'),
('Write the opening paragraph of your autobiography.', 'creative'),
('Create a conversation between your past and future self.', 'creative'),
('Describe an emotion that doesn''t have a name yet.', 'creative'),
('Write a story where the last line is "And that''s how it all began."', 'creative'),
('Imagine you wake up and everyone in the world has disappeared except you. What do you do first?', 'creative'),
('Write a poem using only questions.', 'creative'),
('Describe your city/town as if you were seeing it for the first time.', 'creative'),
('Write a short story inspired by the last song you listened to.', 'creative'),
('Create a character based on someone you saw today but don''t know.', 'creative'),
('Write about an ordinary moment as if it were the most important event in history.', 'creative'),
('Describe what the internet would look like if it were a physical place.', 'creative'),
('Write a fairy tale set in modern times.', 'creative'),
('Imagine you could bottle one feeling. Which would it be and who would you give it to?', 'creative'),
('Write a story that takes place entirely in a waiting room.', 'creative'),
('Describe a photograph that was never taken.', 'creative'),
('Write from the perspective of the moon watching Earth.', 'creative'),
('Create a menu for a restaurant that serves emotions instead of food.', 'creative'),
('Write about a world where music is illegal.', 'creative'),
('Describe the space between two heartbeats.', 'creative'),
('Write a story where the main character is a metaphor.', 'creative'),

-- Opinion (30)
('What''s an unpopular opinion you genuinely hold?', 'opinion'),
('Is social media making us more connected or more isolated?', 'opinion'),
('What''s the most overrated piece of advice people give?', 'opinion'),
('Should we optimize for happiness or meaning in life?', 'opinion'),
('What''s something society considers normal that you find strange?', 'opinion'),
('Is it better to be honest or kind when you can''t be both?', 'opinion'),
('What''s the biggest misconception people have about your generation?', 'opinion'),
('Do you think people can truly change? Why or why not?', 'opinion'),
('What''s a hill you''re willing to die on?', 'opinion'),
('Is nostalgia helpful or harmful?', 'opinion'),
('What''s the most important skill that isn''t taught in school?', 'opinion'),
('Should art be comfortable or challenging?', 'opinion'),
('What does success actually look like to you?', 'opinion'),
('Is it possible to be truly selfless?', 'opinion'),
('What''s the difference between loneliness and being alone?', 'opinion'),
('Do we have a moral obligation to be happy?', 'opinion'),
('What''s more important: talent or persistence?', 'opinion'),
('Is vulnerability a strength or a weakness?', 'opinion'),
('What''s something the world needs less of right now?', 'opinion'),
('Should we judge people by their intentions or their actions?', 'opinion'),
('What''s more valuable: experience or education?', 'opinion'),
('Is ambition a virtue or a vice?', 'opinion'),
('What would you change about how we communicate today?', 'opinion'),
('Is privacy a right or a privilege in the digital age?', 'opinion'),
('What''s more important for creativity: constraints or freedom?', 'opinion'),
('Do you believe in second chances? Under what conditions?', 'opinion'),
('What''s the most important conversation we''re not having?', 'opinion'),
('Is perfectionism productive or destructive?', 'opinion'),
('What does the world need more of right now?', 'opinion'),
('Is it better to specialize or be a generalist?', 'opinion'),

-- Memory (30)
('Describe your earliest memory in vivid detail.', 'memory'),
('Write about a meal that meant more than just food.', 'memory'),
('What''s a small moment that you think about more than you should?', 'memory'),
('Describe the best day of your life so far.', 'memory'),
('Write about a place you can never go back to.', 'memory'),
('What''s a conversation that changed the course of your life?', 'memory'),
('Describe the first time you felt truly independent.', 'memory'),
('Write about a goodbye that still lingers.', 'memory'),
('What''s a tradition from your childhood that you still carry?', 'memory'),
('Describe a teacher who left a lasting impact on you.', 'memory'),
('Write about a risk that paid off.', 'memory'),
('What''s the most beautiful thing you''ve ever witnessed?', 'memory'),
('Describe a friendship that shaped who you are.', 'memory'),
('Write about a time you got completely lost, literally or figuratively.', 'memory'),
('What''s a gift you received that meant more than the giver realized?', 'memory'),
('Describe the soundtrack of a specific period in your life.', 'memory'),
('Write about a promise you made and kept.', 'memory'),
('What''s a smell that instantly transports you somewhere?', 'memory'),
('Describe a moment of pure, uncomplicated happiness.', 'memory'),
('Write about something you built with your own hands.', 'memory'),
('What''s the longest you''ve ever waited for something? Was it worth it?', 'memory'),
('Describe a stranger who made a difference in your day.', 'memory'),
('Write about the first time you felt like you belonged.', 'memory'),
('What''s a secret place from your childhood?', 'memory'),
('Describe a storm you remember, actual or metaphorical.', 'memory'),
('Write about a book or movie that changed your perspective.', 'memory'),
('What''s the funniest thing that ever happened to you?', 'memory'),
('Describe a moment of unexpected connection with someone.', 'memory'),
('Write about the last thing that made you cry happy tears.', 'memory'),
('What''s a lesson you learned from losing something?', 'memory'),

-- Observation (30)
('Describe what you see right now in the most interesting way possible.', 'observation'),
('Write about a pattern you''ve noticed in human behavior.', 'observation'),
('What''s something beautiful that most people walk past without noticing?', 'observation'),
('Describe the light at this exact moment.', 'observation'),
('Write about the sounds around you right now and what they tell you.', 'observation'),
('What''s a small detail about someone you love that you''ve never told them you notice?', 'observation'),
('Describe the way a specific person laughs.', 'observation'),
('Write about something you observed today that made you think.', 'observation'),
('What does your morning routine reveal about who you are?', 'observation'),
('Describe the energy of the space you''re in right now.', 'observation'),
('Write about something that''s ending that not enough people are paying attention to.', 'observation'),
('What''s the most interesting thing about the people around you right now?', 'observation'),
('Describe how your neighborhood has changed since you first knew it.', 'observation'),
('Write about body language you noticed in a recent interaction.', 'observation'),
('What''s something old that''s more beautiful than its modern replacement?', 'observation'),
('Describe the weather today as if it were a character in a story.', 'observation'),
('Write about a texture that you find comforting.', 'observation'),
('What''s the most interesting thing you''ve overheard recently?', 'observation'),
('Describe the last sunset or sunrise you actually stopped to watch.', 'observation'),
('Write about a building that has personality.', 'observation'),
('What''s something you noticed today for the first time despite seeing it hundreds of times?', 'observation'),
('Describe the difference between how a place looks and how it feels.', 'observation'),
('Write about the objects on your desk and what they say about you.', 'observation'),
('What''s the most interesting face you''ve seen recently?', 'observation'),
('Describe a moment of silence you experienced today.', 'observation'),
('Write about the gap between expectation and reality in a recent experience.', 'observation'),
('What does your handwriting look like, and what do you think it says about you?', 'observation'),
('Describe the journey between two places you travel between regularly.', 'observation'),
('Write about something man-made that looks natural, or something natural that looks man-made.', 'observation'),
('What small change in your daily environment would make the biggest difference?', 'observation');
